tests/nu/master_add_projusr2_to_project2_as_projadm2: add reset, push -f origin/master

diff --git a/tests/nu/master_add_projusr2_to_project2_as_projadm2 b/tests/nu/master_add_projusr2_to_project2_as_projadm2
--- a/tests/nu/master_add_projusr2_to_project2_as_projadm2
+++ b/tests/nu/master_add_projusr2_to_project2_as_projadm2
@@ -2,26 +2,47 @@
 
 run() {
 	set -e
+	. tests/b/utils
 	pcrt=$(readlink -f ./apache/crts)
-	source tests/b/utils
 	cd tests/newusers/gitolite-admin_as_projadm2
-	git config http.https://localhost:6443/.sslCAInfo "${pcrt}"
-	git config credential.helper passwd
-	git config core.pager cat
-	git config push.default simple
-	git config user.name projadm2
-	git config user.email projadm@email.com
+	pwd
+	git_config 6443 "${pcrt}" "projadm2"
 	git checkout master &2>/dev/null
+
+	if [ ${reset} -eq 0 ]; then
+		echo "resetting to 'Add new repo module2 to project2 group'"
+		check=$(git log --format=format:%H --grep "Add new repo module2 to project2 group$" master)
+		if [ "check" = "" ]; then
+			echo "Impossible to reset: 'Add new repo module2 to project2 group$' not found" >> ${dirp0}/tests/err
+			return -1
+		fi
+		git reset --hard ${check}
+		reset=1
+	fi
+
+	set +e
+	check=$(git branch --no-color --contains "origin/master" | grep -e " master$" 2>&1)
+	if [ "${check}" = "" ]; then
+		echo "must reset origin/master"
+		git remote set-url origin https://projextrdr@localhost:6443/hgit/gitolite-admin
+		git push -f origin master
+		git remote set-url origin https://projadm2@localhost:6443/hgit/gitolite-admin
+	fi
+	set -e
+
 	pconf="conf/subs/project2.conf"
 	# git reset ${gconf}
 	# git checkout ${gconf}
 	append_one "RW\s\+=\s\+projusr2" "${pconf}" "		RW	= projusr2"
-
+	if [ ${append} -lt 0 ]; then
+		echo "Incorrect number of projusr2 in '${pconf}'">> ${dirp0}/tests/err
+		return -1
+	fi
 	if [ ${append} -eq 0 ]; then
 		git_status_diff_add_commit_log "${pconf}" "Add projusr2 to project2 as projadm2"
 	fi
 	echo "dirp0='${dirp0}' vs. pcrt='${pcrt}'"
-	check_if_pushed "origin" "[Aa]dd projusr2 to project2.*" "master"
+	check_if_pushed "origin" "[Aa]dd projusr2 to project2 as projadm2$" "master"
 	if [ "${check}" = "" ]; then
 		echo "no commit 'Add projusr2 to project2 as projadm2">> ${dirp0}/tests/err
 		return 1
