nginx run/kill, calls apache

diff --git a/nginx/run b/nginx/run
--- a/nginx/run
+++ b/nginx/run
@@ -1,5 +1,11 @@
 #! /bin/sh
-. ../.bash_aliases
+
+folder="$( cd "$( dirname "$(readlink -f "$0")" )" && pwd )"
+cd ${folder}
+. ${folder}/../scripts/.bash_aliases
+
+image="kv:5000/b2d/nginx:1.6.2"
+
 cd $HOME/b2d/apache
 ./run $1
 cd $HOME/b2d/nginx
@@ -14,16 +20,21 @@ if [ "${1}" != "" ]; then
 	nginx_cont="nginx.${1}.cont"
 	envs_cnf="envs.${1}.cnf"
 	crt="nginx.${1}.crt"
+	env=$1
 fi
+if [ "${1}" == "" ]; then env="none"; fi
+
 
 port_https=$(sed -n "s#^\s*@PORT_NGINX_HTTPS@\s*=\s*##p" ../envs/${envs_cnf})
 if [ "${port_https}" = "" ]; then echo "missing @PORT_NGINX_HTTPS@ in '$HOME/b2d/envs/${envs_cnf}'"; exit 0; fi
 port_http=$(sed -n "s#^\s*@PORT_NGINX_HTTP@\s*=\s*##p" ../envs/${envs_cnf})
 if [ "${port_http}" = "" ]; then echo "missing @PORT_NGINX_HTTP@ in '$HOME/b2d/envs/${envs_cnf}'"; exit 0; fi
 
-docker inspect ${apache_cont} > /dev/null 2>&1 || { echo "${nginx_cont}/run: apache_cont '${apache_cont}' not started"; exit 1; }
+docker network inspect br${env}  > /dev/null 2>&1 || { echo "network br${env} not created: apache cannot join"; exit 1; }
+
+docker inspect ${apache_cont} > /dev/null 2>&1 || { echo "${nginx_cont}/run: apache_cont '${apache_cont}' not started"; }
 docker inspect ${nginx_cont} > /dev/null 2>&1 && if [ "$(din -f '{{.State.ExitCode}}' ${nginx_cont})" != "0" ]; then
 	d rm ${nginx_cont}
 fi
-docker inspect ${nginx_cont} > /dev/null 2>&1 || docker run -it -d --name ${nginx_cont} -p ${port_http}:80 -p ${port_https}:443 --link ${apache_cont}:nginx.apache.cont nginx
-docker cp ${nginx_cont}:/home/git/nginx/itsvc.world.company.crt "$(readlink -f $HOME/b2d)/nginx/${crt}"
+docker inspect ${nginx_cont} > /dev/null 2>&1 || docker run -it -d --name ${nginx_cont} -p ${port_http}:80 -p ${port_https}:443 --net=br${env} ${image}
+docker cp ${nginx_cont}:/home/git/nginx/itsvc.world.company.crt "${folder}/${crt}"
