gitolite/build: uses index Mounts 0 .Sources instead of pre 1.8 .Volumes

diff --git a/gitolite/build b/gitolite/build
--- a/gitolite/build
+++ b/gitolite/build
@@ -1,5 +1,7 @@
 #! /bin/sh
 
+cd $HOME/b2d/gitolite
+
 gitolite_cont="gitolite.cont"
 gitolite_repos_cont="gitolite.repos.cont"
 grepos="grepos"
@@ -11,10 +13,15 @@ if [[ "${1}" != "" && "${1}" != "bash" ]]; then
 fi
 
 if [ "$(docker images -q gitolite.repos 2> /dev/null)" = "" ]; then
-  docker build -t gitolite.repos -f $HOME/b2d/gitolite/Dockerfile.repos $HOME/b2d/gitolite || exit 1
+  docker build -t gitolite.repos -f Dockerfile.repos $HOME/b2d/gitolite || exit 1
 fi
-docker inspect ${gitolite_repos_cont} > /dev/null 2>&1 || docker create --name="${gitolite_repos_cont}" gitolite.repos
-grpath=$(docker inspect -f '{{ index .Volumes "/home/git/repositories" }}' ${gitolite_repos_cont})
+docker inspect ${gitolite_repos_cont} > /dev/null 2>&1 || docker create --name="${gitolite_repos_cont}" gitolite.repos /bin/true
+grpath=$(docker inspect -f '{{ (index .Mounts 0).Source }}' ${gitolite_repos_cont} 2> /dev/null)
+if [ "${grpath}" == "" ]; then
+	echo "unable to find volume for data repo container '${gitolite_repos_cont}'"
+	exit 1
+fi
+
 if [ ! -f $HOME/b2d/gitolite/${grepos} ]; then
 	echo "${grepos}: new container"
 	echo ${grpath}>$HOME/b2d/gitolite/${grepos}
