apache and openldap join br<env>, and set alias

diff --git a/apache/run b/apache/run
--- a/apache/run
+++ b/apache/run
@@ -52,7 +52,9 @@ if [ "${1}" != "" ]; then
 	envs_private=".envs.${1}.private"
 	crt="apache.${1}.crt"
 	mcron_shippingbay_cont="mcron.shippingbay.${1}.cont"
+	env=${1}
 fi
+if [ "${1}" == "" ]; then env="none"; fi
 
 port_gitweb=$(sed -n "s#^\s*@PORT_HTTP_GITWEB@\s*=\s*##p" ../envs/${envs_cnf})
 if [ "${port_gitweb}" = "" ]; then echo "missing @PORT_HTTP_GITWEB@ in '$HOME/b2d/envs/${envs_cnf}'"; exit 0; fi
@@ -70,7 +72,10 @@ docker inspect ${gitolite_cont} > /dev/null 2>&1 || { echo "${apache_cont}/run: 
 
 # TODO: warning --link openldap.cont:apache.openldap.cont
 # TODO: add network
-alias drapache="docker run -it -d --name ${apache_cont} -p ${port_gitweb}:8543 -p ${port_hgit}:8553 $(dvv ${gitolite_repos_cont}) --volumes-from ${gitolite_cont} $(dvv ${gnupg2_cont})"
+
+docker network inspect br${env}  > /dev/null 2>&1 || { echo "network br${env} not created: apache cannot join"; exit 1; }
+
+alias drapache="docker run -it -d --name ${apache_cont} -p ${port_gitweb}:8543 -p ${port_hgit}:8553 $(dvv ${gitolite_repos_cont}) --volumes-from ${gitolite_cont} $(dvv ${gnupg2_cont}) --net=br${env}"
 
 if [ -z "${upstream}" ] && [ -z "${downstream}" ]; then
 	if [ "${1}" = "external" ]; then
diff --git a/openldap/run b/openldap/run
--- a/openldap/run
+++ b/openldap/run
@@ -6,11 +6,16 @@ cd ${folder}
 
 image="kv:5000/b2d/openldap:2.4.31"
 
+env=$1
+if [ "${1}" == "" ]; then env="none"; fi
+
+docker network inspect br${env}  > /dev/null 2>&1 || { echo "network br${env} not created: openldap cannot join"; exit 1; }
+
 ec=$(docker inspect -f '{{ .State.Running }}' openldap.cont 2> /dev/null)
 if [ "${ec}" = "false" ]; then
 	docker rm openldap.cont
 fi
-docker inspect openldap.cont > /dev/null 2>&1 || d run -d --name openldap.cont ${image}
+docker inspect openldap.cont > /dev/null 2>&1 || d run -d --name openldap.cont --net=br${env} --net-alias=apache.openldap.cont ${image}
 docker inspect openldap.cont > /dev/null 2>&1 || exit 0
 i=$(docker exec -u git openldap.cont ./openldap/ini_ldap_db.sh 2>&1)
 [ ! -z "${verbose}" ] && echo "${i}"
